# Generated by Django 4.2.4 on 2023-08-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_size_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizevariant',
            name='price',
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
