# Generated by Django 4.2.4 on 2023-08-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_sizevariant_price_sizevariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_variant',
            field=models.ManyToManyField(blank=True, related_name='size', to='product.sizevariant'),
        ),
    ]
