# Generated by Django 4.2.4 on 2023-08-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_size_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizevariant',
            name='product',
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='product',
            field=models.ManyToManyField(null=True, to='product.product'),
        ),
    ]
